### PR TITLE
status RPC: print vusb device ID

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Build here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1531

**Review by eric-ch — APPROVED** [review]
LGTM.

**Comment by eric-ch** [comment]
Ca you PR against stable-8 as well please?

**Comment by eric-ch** [comment]
Will merge soon.

**Pull request merged**
